- name: Ensure vm.max_map_count is set permanently
  ansible.builtin.copy:
    dest: /etc/sysctl.d/99-vm-max-map-count.conf
    content: "vm.max_map_count=262144\n"
    owner: root
    group: root
    mode: '0644'

- name: Reload sysctl to apply changes
  ansible.builtin.command: sysctl --system
  changed_when: true

- name: Ensure Git is installed
  ansible.builtin.apt:
    name: git
    state: present
    update_cache: yes

- name: Clone wazuh-docker repository
  ansible.builtin.git:
    repo: https://github.com/wazuh/wazuh-docker.git
    dest: /opt/wazuh-docker
    version: v4.12.0

- name: Generate indexer certificates
  ansible.builtin.command:
    cmd: docker compose -f generate-indexer-certs.yml run --rm generator
    chdir: /opt/wazuh-docker/single-node
  changed_when: true

- name: Start Wazuh single-node with Docker Compose
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: /opt/wazuh-docker/single-node
  changed_when: true
